INSERT INTO CONFIGURATIONS (KEY, VALUES) VALUES ('RATE_DELIVERY', ARRAY['5.99']);
INSERT INTO CONFIGURATIONS (KEY, VALUES) VALUES ('OPENING_HOURS', ARRAY['08', '00']);
INSERT INTO CONFIGURATIONS (KEY, VALUES) VALUES ('CLOSING_TIME', ARRAY['18', '00']);
INSERT INTO CONFIGURATIONS (KEY, VALUES) VALUES ('OPENING_DAYS', ARRAY['seg.', 'ter.', 'qua.', 'qui.', 'sex.', 'sáb.']);
INSERT INTO CONFIGURATIONS (KEY, VALUES) VALUES ('DELIVERY_FORECAST_MINUTE', ARRAY['90']);