INSERT INTO PAYMENTS_METHODS (ID, TYPE) VALUES (1, 'Cartão de crédito');
INSERT INTO PAYMENTS_METHODS (ID, TYPE) VALUES (2, 'Cartão de debito');
INSERT INTO PAYMENTS_METHODS (ID, TYPE) VALUES (3, 'PIX');