CREATE TABLE IF NOT EXISTS USERS
(
    ID SERIAL NOT NULL,
    CART_ID BIGINT,
    PASSWORD VARCHAR(300) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    LAST_NAME VARCHAR(50) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_CART_FK FOREIGN KEY (CART_ID) REFERENCES CARTS(ID)
);