CREATE TABLE IF NOT EXISTS ADDRESSES
(
    ID SERIAL NOT NULL,
    USER_ID BIGINT,
    CITY VARCHAR (20) NOT NULL,
    COUNTRY VARCHAR (20),
    NEIGHBORHOOD VARCHAR (50) NOT NULL,
    STATE CHAR (2) NOT NULL,
    STREET VARCHAR (70) NOT NULL,
    TITLE VARCHAR (300),
    ZIPCODE VARCHAR (20),
    CONSTRAINT ADDRESSES_PK PRIMARY KEY (ID),
    CONSTRAINT USER_ADDRESS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)