CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CONSTRAINT USERS_ROLES_PK PRIMARY KEY (ROLE_ID, USER_ID),
    CONSTRAINT USERS_ROLES_USERS_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT USERS_ROLES_ROLES_ID_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
)
