CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID SERIAL NOT NULL,
    DESCRIPTION VARCHAR(30) NOT NULL,
    DETAILS VARCHAR(100),
    PRICE NUMERIC(10, 2) NOT NULL,
    AVAILABLE BOOLEAN DEFAULT TRUE,
    HIGHLIGHT BOOLEAN DEFAULT FALSE,
    FILE_NAME VARCHAR(50),
    IMG_URL VARCHAR(100),
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (ID)
);
