CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID SERIAL NOT NULL,
    DESCRIPTION VARCHAR(30) NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL,
    AVAILABLE BOOLEAN,
    HIGHLIGHT BOOLEAN,
    IMG_URL VARCHAR(100)
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (ID)
);
