CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID SERIAL NOT NULL,
    DESCRIPTION VARCHAR(30) NOT NULL,
    DETAILS VARCHAR(100),
    PRICE NUMERIC(10, 2) NOT NULL,
    HIGHLIGHT BOOLEAN,
    FILE_NAME VARCHAR(50),
    IMG_URL VARCHAR(100),
    CATEGORY_ID BIGINT NOT NULL,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (ID),
    CONSTRAINT CATEGORIES_PRODUCTS_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);
