CREATE TABLE IF NOT EXISTS ORDERS
(
    ID SERIAL NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    DATE_TIME TIMESTAMP NOT NULL,
    TOTAL NUMERIC(10, 2) NOT NULL,
    OBSERVATIONS VARCHAR(100),
    DELIVERY BOOLEAN NOT NULL,
    DELIVERY_FORECAST TIMESTAMP NOT NULL,
    RATE_DELIVERY NUMERIC(10, 2) NOT NULL,
    USER_ID BIGINT NOT NULL,
    PAYMENT_METHOD_ID BIGINT NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_ORDERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT PAYMENTS_METHODS_ORDERS_FK FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENTS_METHODS(ID),
    CONSTRAINT ADDRESSES_ORDERS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESSES(ID)
);
